apiVersion: v1
kind: Service
metadata:
  name: webapp-nodeport
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodeport: 3000
  selector:
    app: webapp
