apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v2
  labels:
    app: webapp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-ecr
          image: 015092641389.dkr.ecr.us-east-1.amazonaws.com/db-ecr:v0.1
          env:
            - name: DBPWD
              value: pwdanuj
            - name: DBPORT
              value: "3306"
            - name: DBHOST
              value: "db.default.svc.cluster.local"
            - name: DBUSER
              value: "root"
          ports:
            - containerPort: 8080
