apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-v2
  labels:
    app: dbapp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: dbapp

  template:
    metadata:
      labels:
        app: dbapp
    spec:
      containers:
        - name: db-ecr
          image: 015092641389.dkr.ecr.us-east-1.amazonaws.com/db-ecr:v0.2
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pwdanuj
          ports:
            - containerPort: 3306
