apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: db

spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 1
      
  template:
    metadata:
      labels:
        app: app
        
    spec:
      containers:
        - name: db-ecr
          image: 015092641389.dkr.ecr.us-east-1.amazonaws.com/db-ecr:v0.1
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pwdanuj
          ports:
            - containerPort: 3306
